[build]
  command = "gatsby build"
  publish = "public"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/site/*"
  to = "/site-template.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/site-dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
